
package com.finmex.omnisuite.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CreditoMovimientosSoap", targetNamespace = "http://Mascore/Movimientos")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditoMovimientosSoap {


    /**
     * Consulta los últimos 10 movimientos
     * 
     * @param parameters
     * @return
     *     returns com.finmex.omnisuite.client.MovimientosCredito
     */
    @WebMethod(operationName = "Movimientos_Array", action = "http://Mascore/Movimientos/Movimientos_Array")
    @WebResult(name = "MovimientosCredito", targetNamespace = "http://Mascore/Movimientos/Movimientos_Array/Response", partName = "parameters")
    public MovimientosCredito movimientosArray(
        @WebParam(name = "Parametros", targetNamespace = "http://Mascore/Movimientos/Movimientos_Array/Request", partName = "parameters")
        Parametros parameters);

}
